services:
  dev-app: # PHP+Apacheのサービス
    build: ./dev-app # コンテナのイメージを./phpディレクトリからビルド
    container_name: apache_laravel # コンテナ名
    user: "${UID_GID:-1000:1000}" # ホストマシンと同じユーザー権限でコンテナ内のプロセスを実行
    volumes:
      - ./src:/var/www/html
    ports: 
      - "80:80" # ホストのポート：コンテナのポート
      - "5173:5173" # viteで使用するポートをフォワード
    environment:
      - APACHE_LOG_DIR=/var/log/apache2
      - APP_NAME=${APP_NAME:-Laravel}
      - APP_ENV=${APP_ENV:-local}
      - APP_TIMEZONE=${APP_TIMEZONE:-Asia/Tokyo}
      - APP_LOCALE=${APP_LOCALE:-ja}
      - APP_FALLBACK_LOCALE=${APP_FALLBACK_LOCALE:-ja}
      - APP_FAKER_LOCALE=${APP_FAKER_LOCALE:-ja_JP}
      - DB_CONNECTION=${DB_CONNECTION:-mariadb}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-database}
      - DB_USERNAME=${DB_USERNAME:-user}
      - DB_PASSWORD=${DB_PASSWORD:-password}
    networks:
      - localnet
  db:
    image: mariadb:11.2.5 # MariaDBイメージのバージョンを指定
    container_name: mariadb
    environment: # Compose内の環境変数を指定
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpass}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-database}
      - MYSQL_USER=${MYSQL_USER:-user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - TZ=Asia/Tokyo
    ports:
      - "3306:3306"
    volumes: 
    - type: volume
      source: db-store # 定義済みのボリュームdb-storeを使用
      target: /var/lib/mysql # MariaDBのデータディレクトリにマウント (データ永続化)
    - type: bind
      source: ./mariadb/my.cnf # ホスト側で設定を記述
      target: /etc/mysql/conf.d/my.cnf # MariaDB の設定ファイルとしてマウント
    - type: bind
      source: ./mariadb/init # 初期化時にテーブルの作成やデータの挿入を行う
      target: /docker-entrypoint-initdb.d 
    depends_on:
      - dev-app # PHPコンテナが起動した後にMariaDBコンテナを起動
    networks:
      - localnet
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1 # 任意のホストへの接続を許可
      - PMA_HOST=db # データベースのサービス名を指定
      - PMA_USER=${MYSQL_USER:-user} # データベースユーザー名
      - PMA_PASSWORD=${MYSQL_PASSWORD:-password} # データベースユーザーのパスワード
      - TZ=Asia/Tokyo
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - localnet
  mailhog:
    image: mailhog/mailhog
    container_name: mail_server
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - localnet
volumes:
  db-store: # MariaDBのデータを保存するためのボリューム
networks:
  localnet: